### PR TITLE
Fix compiling with O3 for Paul

### PR DESCRIPTION
**Pull request by cannondalev2000**
even when these are compiled with O3 properly there are some funky display issues last I used an 8660 device so just compile it with Os

### CODE REVIEW

**Comment by javelinanddart** [comment]
Much dev, such wow

**Comment by cannondalev2000** [comment]
Still more than what your lazy ass woulda done

**Comment by cannondalev2000** [comment]
look here bastard https://github.com/InSaNiTy-RoM/android_build/commits/lp5.1
 thats what realy dev work looks like :P

**Comment by javelinanddart** [comment]
LMAO, I patched up stagefright for Os
And I'm talking about this commit bastard :P

**Comment by IronSharpensIron2717** [comment]
Hi Ethan ;~}

**Comment by cannondalev2000** [comment]
Sup Dennis

**Comment by cuzz1369** [comment]
My cats breath smells like cat food.

**Comment by cannondalev2000** [comment]
I wonder why

**Comment by cuzz1369** [comment]
Because it eats cat food probably

**Comment by cannondalev2000** [comment]
lol

**Comment by cannondalev2000** [comment]
So Dennis are you part of the "Blaze" devs too if ya know what I mean :P

**Comment by IronSharpensIron2717** [comment]
"blaze" yes shit devices no

**Comment by cannondalev2000** [comment]
LOL you know caught what I meant

**Pull request merged**
